name: Docker build

on:
    push:
        branches-ignore: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: "Build"
              run: |
                  docker build . -f Dockerfile -t gyro-frontend
